# Generated by Django 3.1.4 on 2020-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WB', 'Bathroom'), ('NB', 'NO-Bathroom')], max_length=5)),
            ],
        ),
    ]
