# Generated by Django 3.1.3 on 2020-12-19 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innapp', '0004_auto_20201219_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ClientProfile',
        ),
    ]
