# Generated by Django 3.1.4 on 2020-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('WB', 'bathroom'), ('NB', 'no bathroom')], max_length=5),
        ),
    ]
