# Generated by Django 3.1.4 on 2020-12-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0005_auto_20201219_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
