# Generated by Django 3.1.3 on 2020-12-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0006_book_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
